// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart'; 
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrvTeOHaoqWFVa9FaEM5Yysx4NbfPawG4',
    appId: '1:582466235891:web:5013c60d2552ded1e77686',
    messagingSenderId: '582466235891',
    projectId: 'text-extractor-b5b2c',
    authDomain: 'text-extractor-b5b2c.firebaseapp.com',
    storageBucket: 'text-extractor-b5b2c.firebasestorage.app',
    measurementId: 'G-J193S5FEKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfYkO5KET6OZxoOcJLpY8W7hQCigrVYwk',
    appId: '1:582466235891:android:641e2a059a926f4ee77686',
    messagingSenderId: '582466235891',
    projectId: 'text-extractor-b5b2c',
    storageBucket: 'text-extractor-b5b2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ5b90qpvoQ_1735ph5Mz27Qk11YsyESI',
    appId: '1:582466235891:ios:0f9b06f78b8c588fe77686',
    messagingSenderId: '582466235891',
    projectId: 'text-extractor-b5b2c',
    storageBucket: 'text-extractor-b5b2c.firebasestorage.app',
    iosBundleId: 'com.example.textreading',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ5b90qpvoQ_1735ph5Mz27Qk11YsyESI',
    appId: '1:582466235891:ios:0f9b06f78b8c588fe77686',
    messagingSenderId: '582466235891',
    projectId: 'text-extractor-b5b2c',
    storageBucket: 'text-extractor-b5b2c.firebasestorage.app',
    iosBundleId: 'com.example.textreading',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrvTeOHaoqWFVa9FaEM5Yysx4NbfPawG4',
    appId: '1:582466235891:web:3209820f6c96d886e77686',
    messagingSenderId: '582466235891',
    projectId: 'text-extractor-b5b2c',
    authDomain: 'text-extractor-b5b2c.firebaseapp.com',
    storageBucket: 'text-extractor-b5b2c.firebasestorage.app',
    measurementId: 'G-EMS2TWXSBX',
  );
}
